
output:
  - summary
  - success
  - failure

pre-commit:
  jobs:
    - name: bin-src-format
      root: "bin-src/"
      glob:
        - "bin-src/src/*.{js,ts,tsx,jsx}"
        - "bin-src/src/**/*.{js,ts,tsx,jsx}"
      run: npx prettier --write {staged_files}
      stage_fixed: true
      skip:
        - merge
        - rebase

    - name: bin-src-lint
      root: "bin-src/"
      glob:
        - "bin-src/src/*.{js,ts,tsx,jsx}"
        - "bin-src/src/**/*.{js,ts,tsx,jsx}"
      run: npx xo --fix {staged_files}
      stage_fixed: true
      skip:
        - merge
        - rebase
