
output:
  - summary
  - success
  - failure

pre-commit:
  jobs:
    - name: exexutable-format
      root: "executables/"
      glob:
        - "executables/src/*.{js,ts,tsx,jsx}"
        - "executables/src/**/*.{js,ts,tsx,jsx}"
      run: npx prettier --write {staged_files}
      stage_fixed: true
      skip:
        - merge
        - rebase
